// <auto-generated />
using System;

using BlocklistAPI.Context;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

using MySql.EntityFrameworkCore.Extensions;

#nullable disable

namespace BlocklistAPI.Migrations
{
    [DbContext(typeof(ocartDbContext))]
    [Migration("20250109095816_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            // MySQLModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BlocklistAPI.Models.FileType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySQLPropertyBuilderExtensions.UseMySQLAutoIncrementColumn(b.Property<int>("ID"), "int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "Name" }, "IX_FileType_Name")
                        .IsUnique();

                    b.ToTable("FileType");
                });

            modelBuilder.Entity("BlocklistAPI.Models.RemoteSite", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySQLPropertyBuilderExtensions.UseMySQLAutoIncrementColumn( b.Property<int>("ID"), "int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("FileTypeID")
                        .HasColumnType("int");

                    b.Property<string>("FileUrls")
                        .IsRequired()
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("LastDownloaded")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MinimumIntervalMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SiteUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "FileTypeID" }, "IX_RemoteSite_FileTypeID");

                    b.HasIndex(new[] { "Name", "SiteUrl" }, "IX_RemoteSite_Name")
                        .IsUnique();

                    b.ToTable("RemoteSite");
                });

            modelBuilder.Entity("BlocklistAPI.Models.RemoteSite", b =>
                {
                    b.HasOne("BlocklistAPI.Models.FileType", "FileType")
                        .WithMany("RemoteSites")
                        .HasForeignKey("FileTypeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FileType");
                });

            modelBuilder.Entity("BlocklistAPI.Models.FileType", b =>
                {
                    b.Navigation("RemoteSites");
                });
#pragma warning restore 612, 618
        }
    }
}
