// <auto-generated />
using System;
using BlocklistAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlocklistAPI.Migrations
{
    [DbContext(typeof(ocartDbContext))]
    partial class ocartDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BlocklistAPI.Models.Device", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("MACAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "MACAddress" }, "UC_Device_MACAddress")
                        .IsUnique();

                    b.ToTable("Device", (string)null);
                });

            modelBuilder.Entity("BlocklistAPI.Models.DeviceRemoteSite", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int>("DeviceID")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastDownloaded")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RemoteSiteID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "DeviceID" }, "IX_DeviceRemoteSite_DeviceID");

                    b.HasIndex(new[] { "DeviceID", "RemoteSiteID" }, "IX_DeviceRemoteSite_DeviceID_RemoteSiteID")
                        .IsUnique();

                    b.HasIndex(new[] { "RemoteSiteID" }, "IX_DeviceRemoteSite_RemoteSiteID");

                    b.ToTable("DeviceRemoteSite", (string)null);
                });

            modelBuilder.Entity("BlocklistAPI.Models.FileType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "Name" }, "IX_FileType_Name")
                        .IsUnique();

                    b.ToTable("FileType");
                });

            modelBuilder.Entity("BlocklistAPI.Models.RemoteSite", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<sbyte>("Active")
                        .HasColumnType("TINYINT");

                    b.Property<int>("FileTypeID")
                        .HasColumnType("int");

                    b.Property<string>("FileUrls")
                        .IsRequired()
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("LastDownloaded")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MinimumIntervalMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SiteUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.HasIndex(new[] { "FileTypeID" }, "IX_RemoteSite_FileTypeID");

                    b.HasIndex(new[] { "Name", "SiteUrl" }, "IX_RemoteSite_Name")
                        .IsUnique();

                    b.ToTable("RemoteSite", (string)null);
                });

            modelBuilder.Entity("BlocklistAPI.Models.DeviceRemoteSite", b =>
                {
                    b.HasOne("BlocklistAPI.Models.Device", "Device")
                        .WithMany("DeviceRemoteSites")
                        .HasForeignKey("DeviceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlocklistAPI.Models.RemoteSite", "RemoteSite")
                        .WithMany()
                        .HasForeignKey("RemoteSiteID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("RemoteSite");
                });

            modelBuilder.Entity("BlocklistAPI.Models.RemoteSite", b =>
                {
                    b.HasOne("BlocklistAPI.Models.FileType", "FileType")
                        .WithMany("RemoteSites")
                        .HasForeignKey("FileTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FileType");
                });

            modelBuilder.Entity("BlocklistAPI.Models.Device", b =>
                {
                    b.Navigation("DeviceRemoteSites");
                });

            modelBuilder.Entity("BlocklistAPI.Models.FileType", b =>
                {
                    b.Navigation("RemoteSites");
                });
#pragma warning restore 612, 618
        }
    }
}
